'use strict';
// Real Electron views + real loopback HTTP; no account, credentials or device execution.
const { app, BrowserWindow, WebContentsView, session, ipcMain } = require('electron');
const http = require('node:http');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const { randomUUID } = require('node:crypto');
const { createWebControls, registerWebControls } = require('../native/web-controls.cjs');
const pause = ms => new Promise(resolve => setTimeout(resolve,ms));
// Chromium may reject a snapshot while the compositor swaps surfaces. Retry
// only this read, never navigation, an action or a message submission.
async function capture(contents, rect, options) {
  for(let attempt=0;attempt<3;attempt++) {
    try { return await contents.capturePage(rect,options); }
    catch(error) { if(attempt===2 || !String(error).includes('UnknownVizError')) throw error; await pause(250); }
  }
}
app.setPath('userData',path.join(__dirname,'../.data/preview-fixture-profile-'+randomUUID()));

app.whenReady().then(async () => {
  let window, bridge, host, surfaces, server, controls;
  try {
    const { WebBridge } = await import('../native/web-bridge.mjs');
    const { createWebServer } = await import('../web-server.mjs');
    const { createStudioSurfaces } = await import('../native/studio-surfaces.mjs');
    let siteVersion='Primeira versão';
    const site = name => `<!doctype html><html><meta charset="utf-8"><style>body{margin:0;background:#f4f0ff;font:16px system-ui;color:#27203d}nav{padding:22px;background:white;display:flex;justify-content:space-between}main{padding:70px 38px}h1{font-size:46px;line-height:1.1}p{line-height:1.8;color:#716482}button{padding:14px 22px;border:0;background:#6042b5;color:white;border-radius:10px}.card{background:white;padding:24px;border-radius:18px;margin-top:38px}</style><nav><strong>${name}</strong><span>Produtos · Contato</span></nav><main><span>PROJETO EM CONSTRUÇÃO</span><h1>${name==='Loja Aurora'?'Ideias que ganham forma.':'Uma nova experiência.'}</h1><p>${siteVersion} · preview de teste local.</p><button onclick="document.querySelector('.card').textContent='Interação confirmada'">Explorar coleção</button><div class="card">Resultado gerado no projeto</div></main><script>document.body.dataset.native=String(typeof window.require);document.body.dataset.ordax=String(typeof window.ordaxStudioWebHost)</script></html>`;
    server=http.createServer((req,res)=>{ if(req.url==='/redirect'){res.writeHead(302,{Location:host.origin+'/src/index.html'});res.end();return;}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(site(req.url==='/game'?'Jogo Nebula':'Loja Aurora')); });
    await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const siteURL=`http://127.0.0.1:${server.address().port}/`;
    const isolated=session.fromPartition('studio-preview-chat-fixture-'+randomUUID());
    await isolated.protocol.handle('https',request=>new Response(`<!doctype html><meta charset="utf-8"><title>ChatGPT simulado</title><style>body{background:#171717;color:white;font:16px system-ui;padding:28px}#prompt-textarea{border:1px solid #555;padding:18px}</style><button data-testid="model-switcher-dropdown-button">Modelo de teste</button><main id="turns"><h2>ChatGPT Web · mesma sessão</h2><p>Esta página só aparece quando você solicita.</p></main><form data-chatgpt-composer><div role="tablist" aria-label="Conversation mode"><button type="button" role="tab" aria-selected="${new URL(request.url).pathname.startsWith('/c/') ? 'true' : 'false'}" onclick="this.setAttribute('aria-selected','true');this.nextElementSibling.setAttribute('aria-selected','false')">Chat</button><button type="button" role="tab" aria-selected="${new URL(request.url).pathname.startsWith('/c/') ? 'false' : 'true'}" onclick="this.setAttribute('aria-selected','true');this.previousElementSibling.setAttribute('aria-selected','false')">Work</button></div><div id="prompt-textarea" contenteditable="true"></div><button type="button" aria-label="Dictate" onclick="document.getElementById('prompt-textarea').innerText+='Texto ditado de teste.'">Ditar</button><button type="button" aria-label="Start voice mode" onclick="document.body.dataset.voiceStarted='true'">Voz</button><button type="submit" data-testid="send-button">Enviar</button></form><script>document.querySelector('form').addEventListener('submit',event=>{event.preventDefault();document.body.dataset.sends=String(Number(document.body.dataset.sends||0)+1);const text=document.getElementById('prompt-textarea').innerText;document.getElementById('prompt-textarea').innerHTML='';history.replaceState(null,'','/c/fixture');document.getElementById('turns').innerHTML='<article data-testid="conversation-turn-0" data-turn-id="fixture-user" data-turn="user"><div data-message-author-role="user"></div></article><article data-testid="conversation-turn-1" data-turn-id="fixture-answer" data-turn="assistant"><div data-message-author-role="assistant"><div class="markdown">Resposta com preview fixo.</div></div><button data-testid="copy-turn-action-button">Copiar</button></article>';document.querySelector('[data-message-author-role="user"]').textContent=text;});</script>`,{headers:{'Content-Type':'text/html'}}));
    window=new BrowserWindow({show:false,width:1550,height:900,webPreferences:{preload:path.join(__dirname,'../native/preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true,backgroundThrottling:false}});
    const chat=new WebContentsView({webPreferences:{session:isolated,nodeIntegration:false,contextIsolation:true,sandbox:true,backgroundThrottling:false}});window.contentView.addChildView(chat);
    const disk={},storage={read:async(key,fallback)=>structuredClone(disk[key]||fallback),write:async(key,value)=>{disk[key]=structuredClone(value);}};
    bridge=new WebBridge({surface:chat,storage,interval:100,setupActive:()=>Boolean(controls?.state().pluginSetup)});await bridge.init();
    const views=[],external=[];
    surfaces=createStudioSurfaces({window,chatSurface:chat,project:()=>bridge.projects.find(p=>p.id===bridge.activeProjectId),ownOrigin:()=>host?.origin,openExternal:async url=>external.push(url),createPreviewView:(id,kind='preview')=>{
      const profile=session.fromPartition('fixture-'+kind+'-'+id);profile.setPermissionRequestHandler((_c,_p,callback)=>callback(false));profile.setPermissionCheckHandler(()=>false);profile.on('will-download',event=>event.preventDefault());
      if(kind==='browser')profile.protocol.handle('https',request=>new Response('<!doctype html><meta name="viewport" content="width=device-width"><h1>Site de teste '+new URL(request.url).pathname+'</h1><a href="https://docs.example/next">Outra página</a>',{headers:{'Content-Type':'text/html'}}));
      const view=new WebContentsView({webPreferences:{session:profile,nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true}});views.push(view);return view;
    }});
    controls=createWebControls({window,surface:chat,studioSurfaces:surfaces,isReady:()=>Boolean(bridge.page?.ready),isBusy:()=>Boolean(bridge.run||bridge.sending||bridge.page?.busy),resumeURL:()=>bridge.resumeURL(),openExternal:async url=>external.push(url)});
    host=await createWebServer({bridge});registerWebControls(ipcMain,{window,origin:host.origin,controls});
    for(const [name,action] of Object.entries({state:surfaces.state,reload:surfaces.reload,browser:surfaces.browser,mode:surfaces.setMode,navigate:surfaces.navigate,device:surfaces.setDevice,history:surfaces.history,project:async()=>{await surfaces.sync();return surfaces.state();}}))ipcMain.handle('studio-preview:'+name,(event,value)=>{if(event.sender!==window.webContents||event.senderFrame!==window.webContents.mainFrame||event.senderFrame.url!==host.origin+'/src/index.html')throw new Error('Untrusted IPC sender');return action(value);});
    window.on('resize',controls.layout);controls.layout();await chat.webContents.loadURL('https://chatgpt.com/');await bridge.refresh();await window.loadURL(host.origin+'/src/index.html');
    const js=code=>window.webContents.executeJavaScript(code);
    const until=async code=>{for(let i=0;i<160;i++){if(await js(code))return;await pause(50);}console.error('Fixture state:',JSON.stringify({page:bridge.page,activeId:bridge.activeId,run:Boolean(bridge.run),right:surfaces.state(),browserUI:await js('({location:document.getElementById("previewLocation").value,forwardDisabled:document.getElementById("previewForward").disabled,focused:document.activeElement.id})'),delivery:bridge.chats.find(c=>c.id===bridge.activeId)?.delivery,ui:await js('({notice:document.getElementById("notice").textContent,messages:document.getElementById("messages").textContent,promptDisabled:document.getElementById("prompt").disabled})')}));throw new Error('UI timeout: '+code);};
    await until('document.body.classList.contains("studio-preview") && !document.getElementById("prompt").disabled && document.getElementById("conversationTitle").textContent==="Início"');
    assert.equal(bridge.activeId,null);assert.equal(bridge.activeProjectId,null);assert.equal(await js('document.getElementById("conversationTitle").textContent'),'Início');
    await pause(250);await fs.writeFile(path.join(__dirname,'../.data/studio-home-ui.png'),(await capture(window,undefined,{stayHidden:true,stayAwake:true})).toPNG());
    console.log('PASS PREVIEW: abertura mostra Início sem conversa nem projeto selecionados.');
    await until('document.body.classList.contains("studio-preview") && getComputedStyle(document.querySelector(".web-panel")).display==="none"');
    assert.equal(chat.getVisible(),false);assert.equal(await js('getComputedStyle(document.querySelector(".web-panel")).display'),'none');
    console.log('PASS PREVIEW: coluna direita mostra preview por padrão e a sessão ChatGPT permanece conectada e oculta.');
    await js('document.getElementById("homeWorkspace").click()');
    await until('document.getElementById("projectEntryDialog").open && !document.getElementById("entryConnection").hidden');
    assert.equal(await js('document.getElementById("projectDialog").hidden && document.getElementById("entryDeviceField").hidden'),true);
    await js('document.getElementById("entryFolderTab").click()');
    assert.equal(await js('document.getElementById("entryImportSubmit").disabled && document.getElementById("entryCreate").hidden'),true);
    window.showInactive(); await pause(500); await fs.writeFile(path.join(__dirname,'../.data/studio-open-project-ui.png'),(await capture(window,undefined,{stayHidden:true,stayAwake:true})).toPNG());
    window.hide(); await js('document.getElementById("entryClose").click()');
    console.log('PASS PREVIEW: abrir projeto usa diálogo compacto e bloqueia execução sem sessão ORDAX, sem despejar ferramentas na conversa.');
    await bridge.selectConversationProject((await bridge.createProject({name:'Loja Aurora',instructions:'Use TypeScript para a loja Aurora.',previewUrl:siteURL})).id);
    await until('document.getElementById("projectScopeName").textContent==="Loja Aurora" && document.getElementById("previewEmpty").hidden && !document.getElementById("newChat").disabled');
    const first=views.at(-1), firstContents=first.webContents, projectA=bridge.activeProjectId;
    assert.ok(first.getVisible());assert.ok(first.getBounds().x>chat.getBounds().x);assert.equal(first.webContents.session===isolated,false);
    assert.equal(await first.webContents.executeJavaScript('document.body.dataset.native'),'undefined');assert.equal(await first.webContents.executeJavaScript('document.body.dataset.ordax'),'undefined');assert.ok(!first.webContents.getLastWebPreferences().preload);
    await first.webContents.executeJavaScript('document.querySelector("button").click()');assert.match(await first.webContents.executeJavaScript('document.querySelector(".card").textContent'),/confirmada/);
    console.log('PASS PREVIEW: projeto carrega endereço automaticamente; preview interativo tem sessão isolada e nenhum Node/preload/port OrdaX.');
    await js('document.getElementById("newChat").click()');
    await until('document.body.classList.contains("chatgpt-fallback") && document.getElementById("chatModeStatus").textContent==="Chat confirmado" && !document.getElementById("newChat").disabled');
    for(let i=0;i<80&&!chat.getVisible();i++)await pause(50);
    assert.equal(chat.getVisible(),true);assert.equal(first.getVisible(),true);await bridge.refresh();assert.equal(bridge.state().web.conversationMode,'chat');assert.equal(await chat.webContents.executeJavaScript('document.body.dataset.sends'),undefined);
    await pause(250);await fs.writeFile(path.join(__dirname,'../.data/studio-chat-primary.png'),(await capture(window,undefined,{stayHidden:true,stayAwake:true})).toPNG());
    await js('document.getElementById("fallbackReturn").click()');await until('!document.body.classList.contains("chatgpt-fallback")');
    console.log('PASS MODE: Nova conversa seleciona Chat observado e abre Web como principal à esquerda; Studio é beta e preview fica fixo sem envio.');
    await js('document.getElementById("prompt").value="Desenvolva a próxima etapa";document.getElementById("prompt").dispatchEvent(new Event("input"))');
    await until('!document.getElementById("send").disabled');
    await js('document.getElementById("send").click()');
    await until('document.getElementById("messages").textContent.includes("Resposta com preview fixo") && !document.getElementById("prompt").disabled');
    assert.equal(await chat.webContents.executeJavaScript('document.body.dataset.sends'),'1');assert.equal(chat.getVisible(),false);assert.equal(first.getVisible(),true);
    assert.match(bridge.findChat(bridge.activeId).messages[0].text,/Use TypeScript para a loja Aurora/);
    assert.equal(await js('document.getElementById("prompt").value'),'');
    console.log('PASS PREVIEW: instruções do projeto chegam ao Web no primeiro envio e o recibo limpa o rascunho combinado.');
    console.log('PASS PREVIEW: envio único e resposta sincronizada funcionam com ChatGPT oculto e preview ativo.');
    const audioChat=bridge.activeId;
    await until('!document.getElementById("dictate").disabled && !document.getElementById("voiceChat").disabled');
    await js('document.getElementById("dictate").click()'); await until('!document.getElementById("audioSession").hidden && document.body.classList.contains("chatgpt-fallback")');
    for(let i=0;i<80 && !(await chat.webContents.executeJavaScript('document.getElementById("prompt-textarea").innerText.includes("Texto ditado")'));i++)await pause(50);
    assert.equal(await js('(()=>{const a=document.getElementById("audioSession").getBoundingClientRect(),c=document.getElementById("fallbackCanvas").getBoundingClientRect();return a.height>0 && a.bottom<=c.top && a.width<c.width+1})()'),true);
    await fs.writeFile(path.join(__dirname,'../.data/studio-audio-dictation.png'),(await capture(window,)).toPNG());
    const originalConsume=bridge.consumeWebDraft.bind(bridge); let consumeAttempts=0;
    bridge.consumeWebDraft=async data=>{consumeAttempts++; if(consumeAttempts===1)throw new Error('Falha simulada ao limpar o ditado');return originalConsume(data);};
    await js('document.getElementById("audioFinish").click();document.getElementById("audioFinish").click()');
    await until('document.getElementById("notice").textContent.includes("Falha simulada") && !document.getElementById("audioFinish").disabled');
    assert.equal(consumeAttempts,1); assert.equal(bridge.drafts.state()[audioChat].text,'Texto ditado de teste.');
    await js('document.getElementById("audioFinish").click()'); await until('document.getElementById("audioSession").hidden && !document.body.classList.contains("chatgpt-fallback") && document.getElementById("prompt").value==="Texto ditado de teste."');
    assert.equal(consumeAttempts,2);assert.equal(await chat.webContents.executeJavaScript('document.getElementById("prompt-textarea").innerText'),'');assert.equal(bridge.findChat(audioChat).messages.filter(m=>m.role==='user').length,1);
    assert.equal(first.getVisible(),true);assert.equal(bridge.activeId,audioChat);
    console.log('PASS AUDIO: ditado volta ao rascunho sem envio; falha ao limpar retoma a cópia salva e clique duplicado não repete a operação.');
    await js('document.getElementById("prompt").value="";document.getElementById("prompt").dispatchEvent(new Event("input"))'); await pause(250);await bridge.refresh();
    await until('!document.getElementById("voiceChat").disabled');await js('document.getElementById("voiceChat").click()');await until('!document.getElementById("audioSession").hidden');
    for(let i=0;i<80 && !(await chat.webContents.executeJavaScript('document.body.dataset.voiceStarted==="true"'));i++)await pause(50);
    assert.equal(await chat.webContents.executeJavaScript('document.body.dataset.voiceStarted'),'true');assert.throws(controls.collapse,/Encerre/);
    await js('document.getElementById("audioCancel").click()');await until('document.getElementById("audioSession").hidden && !document.body.classList.contains("chatgpt-fallback")');
    assert.equal(await chat.webContents.executeJavaScript('document.body.dataset.voiceStarted'),undefined);assert.equal(first.getVisible(),true);assert.equal(bridge.activeId,audioChat);
    console.log('PASS AUDIO: voz usa controles Web na área de conversa; cancelar sai da página de áudio e preserva projeto/preview. Microfone real não é simulado como validado.');
    const executeAudio=chat.webContents.executeJavaScript.bind(chat.webContents),loadAudio=chat.webContents.loadURL.bind(chat.webContents);let uncertainAudioClicks=0;
    chat.webContents.executeJavaScript=async(code,...args)=>{const value=await executeAudio(code,...args);if(code.includes('return (function audioControl')){uncertainAudioClicks++;throw new Error('lost audio acknowledgement');}return value;};
    chat.webContents.loadURL=async()=>{throw new Error('audio exit offline');};
    await until('!document.getElementById("webVoice").disabled');await js('document.getElementById("webVoice").click()');
    await until('!document.getElementById("audioSession").hidden && document.getElementById("notice").textContent.includes("encerramento do áudio")');
    assert.equal(uncertainAudioClicks,1);assert.throws(controls.collapse,/Encerre/);assert.equal(await js('document.getElementById("audioCancel").disabled'),false);
    chat.webContents.executeJavaScript=executeAudio;chat.webContents.loadURL=loadAudio;
    await js('document.getElementById("audioCancel").click()');await until('document.getElementById("audioSession").hidden && !document.body.classList.contains("chatgpt-fallback")');
    assert.equal(uncertainAudioClicks,1);assert.equal(await executeAudio('document.body.dataset.voiceStarted'),undefined);assert.equal(first.getVisible(),true);
    console.log('PASS AUDIO: ACK perdido após clique mantém Encerrar disponível e bloqueia ocultar captura; navegação falha não libera o lock, encerramento explícito confirma saída sem repetir voz.');
    for(const [preset,width,height]of [['mobile',390,844],['tablet',768,1024],['desktop',1280,800]]){
      await js(`document.getElementById('previewDevice').value='${preset}';document.getElementById('previewDevice').dispatchEvent(new Event('change'))`);
      await until(`document.getElementById('previewDimensions').textContent.includes('${width} × ${height}')`);await pause(120);
      const size=await first.webContents.executeJavaScript('({width:innerWidth,height:innerHeight})');assert.deepEqual(size,{width,height});
      const bounds=first.getBounds();assert.ok(bounds.x>=Math.floor(window.getContentSize()[0]*0.6)&&bounds.y>=116);
    }
    await js('document.getElementById("previewDevice").value="mobile";document.getElementById("previewDevice").dispatchEvent(new Event("change"))');await until('document.getElementById("previewDimensions").textContent.includes("390 × 844")');
    await js('document.getElementById("previewRotate").click()');await until('document.getElementById("previewDimensions").textContent.includes("844 × 390")');await pause(120);
    assert.equal(await first.webContents.executeJavaScript('innerWidth'),844);
    await js('document.getElementById("previewDevice").value="fit";document.getElementById("previewDevice").dispatchEvent(new Event("change"))');await until('document.getElementById("previewRotate").disabled');
    console.log('PASS PREVIEW: desktop, tablet, celular e rotação mudam o viewport CSS real, com escala limitada ao painel.');
    await js('document.getElementById("prompt").value="Rascunho preservado";document.getElementById("prompt").dispatchEvent(new Event("input"));document.getElementById("webToggle").click()');
    await until('document.body.classList.contains("chatgpt-fallback") && !document.getElementById("chatgptFallback").hidden');
    assert.equal(await js('getComputedStyle(document.querySelector(".app")).visibility'),'visible');
    assert.equal(await js('getComputedStyle(document.getElementById("fallbackReturn")).pointerEvents'),'auto');
    assert.equal(await js('(()=>{const button=document.getElementById("fallbackReturn"),r=button.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===button})()'),true);
    for(let i=0;i<100&&!chat.getVisible();i++)await pause(50);
    assert.equal(chat.getVisible(),true);assert.ok(chat.getBounds().x>0);assert.ok(chat.getBounds().x+chat.getBounds().width<=first.getBounds().x+1);assert.equal(first.getVisible(),true);
    await pause(250);await fs.writeFile(path.join(__dirname,'../.data/studio-preview-fallback.png'),(await capture(window,)).toPNG());
    await js('document.getElementById("accountButton").click()');for(let i=0;i<80&&chat.getVisible();i++)await pause(50);assert.equal(chat.getVisible(),false);
    await js('document.querySelector("[data-close=accountDialog]").click()');for(let i=0;i<80&&!chat.getVisible();i++)await pause(50);assert.equal(chat.getVisible(),true);
    await js('document.getElementById("fallbackReturn").click()');await until('!document.body.classList.contains("chatgpt-fallback") && document.getElementById("prompt").value==="Rascunho preservado"');
    assert.equal(chat.getVisible(),false);assert.equal(first.getVisible(),true);
    console.log('PASS PREVIEW: fallback ocupa somente conversa, preview continua fixo, modais ocultam a superfície nativa e rascunho permanece.');
    siteVersion='Segunda versão';await js('document.getElementById("previewReload").click()');await until('document.getElementById("previewEmpty").hidden && !document.getElementById("previewReload").disabled');
    assert.match(await views.at(-1).webContents.executeJavaScript('document.body.innerText'),/Segunda versão/);assert.equal(firstContents.isDestroyed(),true);
    await js('document.getElementById("previewBrowser").click()');for(let i=0;i<30&&!external.length;i++)await pause(30);assert.deepEqual(external,[siteURL]);
    await pause(250);await fs.writeFile(path.join(__dirname,'../.data/studio-preview-main.png'),(await capture(window,)).toPNG());
    console.log('PASS PREVIEW: atualizar mostra versão nova do site; abrir no navegador usa somente o endereço do projeto.');
    const projectPreview=views.at(-1), browserChat=bridge.activeId;
    await js('document.getElementById("previewMode").value="browser";document.getElementById("previewMode").dispatchEvent(new Event("change"))');await until('document.getElementById("previewStatus").textContent==="Navegador conectado"');
    const browserView=views.at(-1),browserContents=browserView.webContents;assert.equal(projectPreview.getVisible(),false);assert.equal(browserView.getVisible(),true);assert.notEqual(browserContents.session,projectPreview.webContents.session);assert.notEqual(browserContents.session,isolated);
    await js('document.getElementById("previewLocation").value="https://docs.example/start?q=teste";document.getElementById("previewNavigation").requestSubmit()');await until('document.getElementById("previewStatus").textContent==="Navegador conectado" && document.getElementById("previewLocation").value==="https://docs.example/start"');
    assert.equal(await browserContents.executeJavaScript('typeof window.require'),'undefined');assert.equal(await browserContents.executeJavaScript('typeof window.ordaxStudioPreviewHost'),'undefined');
    await browserContents.executeJavaScript('document.querySelector("a").click()');await until('document.getElementById("previewLocation").value==="https://docs.example/next" && document.getElementById("previewStatus").textContent==="Navegador conectado" && !document.getElementById("previewBack").disabled');
    await js('document.getElementById("previewBack").click()');await until('document.getElementById("previewLocation").value==="https://docs.example/start" && !document.getElementById("previewForward").disabled');
    await js('document.getElementById("previewForward").click()');await until('document.getElementById("previewLocation").value==="https://docs.example/next"');
    await js('document.getElementById("previewProjectHost").click()');await until(`document.getElementById('previewLocation').value===${JSON.stringify(siteURL)} && document.getElementById('previewStatus').textContent==='Navegador conectado'`);
    await js('document.getElementById("previewMode").value="preview";document.getElementById("previewMode").dispatchEvent(new Event("change"))');await until('document.getElementById("previewStatus").textContent==="Preview conectado"');
    assert.equal(projectPreview.getVisible(),true);assert.equal(projectPreview.webContents.getURL(),siteURL);assert.equal(bridge.activeId,browserChat);assert.equal(bridge.findProject(projectA).previewUrl,siteURL);
    console.log('PASS PREVIEW: navegador separado abre rede/host, volta e avança; retornar mantém preview, endereço salvo e conversa.');
    await js('document.getElementById("previewMode").value="browser";document.getElementById("previewMode").dispatchEvent(new Event("change"))');await until('document.getElementById("previewMode").value==="browser"');
    await bridge.selectConversationProject((await bridge.createProject({name:'Jogo Nebula',previewUrl:siteURL+'game'})).id);
    await until('document.getElementById("projectScopeName").textContent==="Jogo Nebula" && document.getElementById("previewEmpty").hidden && !document.getElementById("newChat").disabled');
    assert.match(await views.at(-1).webContents.executeJavaScript('document.body.innerText'),/Jogo Nebula/);
    assert.equal(surfaces.state().panelMode,'preview');assert.equal(browserContents.isDestroyed(),true);assert.equal(await js('document.getElementById("previewMode").value'),'preview');
    await js(`document.querySelector('[data-project-id="${projectA}"]').click();`);await until('document.getElementById("projectScopeName").textContent==="Loja Aurora" && document.getElementById("previewEmpty").hidden');
    assert.equal(bridge.activeId,null);await js(`document.querySelector('[data-chat-id="${browserChat}"]').click();`);
    await until('document.getElementById("prompt").value==="Rascunho preservado" && document.body.classList.contains("chatgpt-fallback")');
    await js('document.getElementById("fallbackReturn").click()');await until('!document.body.classList.contains("chatgpt-fallback")');
    await window.webContents.reload();await until('document.getElementById("projectScopeName").textContent==="Loja Aurora" && document.getElementById("previewEmpty").hidden && document.getElementById("prompt").value==="Rascunho preservado"');
    console.log('PASS PREVIEW: trocar projetos carrega host correto; recarregar preserva endereço por projeto e rascunho.');
    const beforePluginURL=chat.webContents.getURL(), beforePluginChat=bridge.activeId;
    await js('document.getElementById("openPlugin").click()');await until('document.getElementById("pluginDialog").open');
    await js('document.getElementById("pluginOpen").click()');await until('!document.getElementById("pluginDialog").open && document.body.classList.contains("chatgpt-fallback") && !document.getElementById("fallbackPluginReturn").hidden');
    for(let i=0;i<80&&!chat.getVisible();i++)await pause(50);
    assert.equal(chat.getVisible(),true);assert.match(chat.webContents.getURL(),/plugins/);assert.equal(surfaces.state().status,'ready');await bridge.refresh();assert.equal(bridge.activeId,beforePluginChat);
    await js('document.getElementById("fallbackPluginReturn").click()');await until('!document.body.classList.contains("chatgpt-fallback") && document.getElementById("prompt").value==="Rascunho preservado"');
    for(let i=0;i<160 && (chat.webContents.getURL()!==beforePluginURL || chat.webContents.isLoading());i++)await pause(50);
    assert.equal(chat.webContents.getURL(),beforePluginURL);assert.equal(chat.getVisible(),false);assert.equal(views.at(-1).getVisible(),true);
    console.log('PASS PREVIEW: cadastro do plugin abre à esquerda sem modal sobreposto e retorna à mesma conversa, com preview e rascunho preservados.');
    await js('document.getElementById("conversationProjectOptions").click();document.getElementById("conversationProjectPreviewUrl").value="https://chatgpt.com/";document.getElementById("saveConversationProject").click()');
    await until('document.getElementById("conversationProjectDialogStatus").textContent.includes("Use HTTPS")');assert.equal(bridge.findProject(projectA).previewUrl,siteURL);
    await js(`document.getElementById('conversationProjectPreviewUrl').value=${JSON.stringify(siteURL+'redirect')};document.getElementById('saveConversationProject').click();`);await until('document.getElementById("previewStatus").textContent==="Preview indisponível"');
    assert.match(surfaces.state().message,/sair do endereço/);assert.equal(views.at(-1).getVisible(),false);
    console.log('PASS PREVIEW: endereço de login é rejeitado e redirecionamento para UI privilegiada é bloqueado sem exibir conteúdo antigo.');
    const keptChat=bridge.activeId,keptURL=chat.webContents.getURL();const unbound=await bridge.createChat({projectId:projectA});await bridge.selectChat(keptChat);await bridge.refresh();
    await until(`document.querySelector('[data-chat-options="${unbound.id}"]') && document.getElementById('prompt').value==='Rascunho preservado' && !document.getElementById('chatOptions').disabled`);
    await js(`document.querySelector('[data-chat-options="${unbound.id}"]').click()`);await until('document.getElementById("optionsDialog").open');
    assert.equal(await js('document.getElementById("deleteScope").querySelector("[value=web]").disabled'),true);assert.equal(bridge.activeId,keptChat);assert.equal(chat.webContents.getURL(),keptURL);
    await js('document.getElementById("deleteChat").click();document.getElementById("deleteChat").click()');await until('!document.getElementById("optionsDialog").open');
    assert.ok(!bridge.chats.some(c=>c.id===unbound.id));assert.equal(bridge.activeId,keptChat);assert.equal(chat.webContents.getURL(),keptURL);assert.equal(await js('document.getElementById("prompt").value'),'Rascunho preservado');
    console.log('PASS DELETE: menu da lateral exclui conversa não ativa, sem abri-la ou trocar URL, projeto e rascunho da conversa atual.');
    const deleteId=bridge.activeId,deleteWeb=bridge.findChat(deleteId).webId;
    assert.ok(deleteWeb);
    await chat.webContents.executeJavaScript(`(()=>{
      const row=document.createElement('li'),link=document.createElement('a'),options=document.createElement('button');link.href='https://chatgpt.com/c/${deleteWeb}';link.textContent='ChatGPT simulado';options.setAttribute('aria-label','Open conversation options');options.textContent='Opções';row.append(link,options);document.body.prepend(row);
      options.onclick=()=>{const menu=document.createElement('button');menu.setAttribute('role','menuitem');menu.textContent='Delete';document.body.append(menu);menu.onclick=()=>{menu.remove();const dialog=document.createElement('div');dialog.setAttribute('role','dialog');dialog.textContent='Delete chat ChatGPT simulado';const button=document.createElement('button');button.textContent='Delete';dialog.append(button);document.body.append(dialog);button.onclick=()=>{document.body.dataset.deletes=String(Number(document.body.dataset.deletes||0)+1);row.remove();dialog.remove();history.replaceState(null,'','/');const toast=document.createElement('div');toast.setAttribute('role','alert');toast.textContent='Chat deleted';document.body.append(toast);};};};
    })()`);
    await js('document.getElementById("chatOptions").click()');await until('document.getElementById("optionsDialog").open');
    await js('document.getElementById("deleteScope").value="web";document.getElementById("deleteScope").dispatchEvent(new Event("change"));document.getElementById("deleteChat").click()');
    assert.equal(await chat.webContents.executeJavaScript('document.body.dataset.deletes'),undefined);assert.ok(bridge.chats.some(c=>c.id===deleteId));
    await js('document.getElementById("deleteChat").click();document.getElementById("deleteChat").click()');
    await until('!document.getElementById("optionsDialog").open && document.getElementById("conversationTitle").textContent==="Loja Aurora"');
    assert.equal(await chat.webContents.executeJavaScript('document.body.dataset.deletes'),'1');assert.ok(!bridge.chats.some(c=>c.id===deleteId));assert.equal(disk['chat-deletions'].find(item=>item.webId===deleteWeb).status,'confirmed');assert.equal(bridge.activeProjectId,projectA);assert.equal(bridge.activeId,null);
    console.log('PASS DELETE: exclusão Web exige confirmação explícita e confirmação visível; clique único, diário durável e histórico local atualizado sem remover o projeto.');
    surfaces.close();await bridge.close();await host.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));window.destroy();app.exit(0);
  } catch(error) {console.error(error);surfaces?.close();await bridge?.close().catch(()=>{});await host?.close().catch(()=>{});server?.closeAllConnections();server?.close();if(window&&!window.isDestroyed())window.destroy();app.exit(1);}
});
